# Las razones no son necesariamente errores, asi que
# tienen su clase definida pero no como exceptions

class Razon:
    pass
# ðŸ‘† class padre